--New role

-- Use an admin role
USE ROLE ACCOUNTADMIN;

-- Create the `dbt` role
CREATE ROLE IF NOT EXISTS dbt COMMENT='This role has all privileges ANALYTICS database';
GRANT ROLE dbt TO ROLE ACCOUNTADMIN;

-- Create the default warehouse if necessary
CREATE WAREHOUSE IF NOT EXISTS DBT_WH;
GRANT OPERATE ON WAREHOUSE DBT_WH TO ROLE dbt;

/*
-- Create the `dbt` user and assign to role
CREATE USER IF NOT EXISTS dbt
  PASSWORD='dbtPassword123'
  LOGIN_NAME='dbt'
  MUST_CHANGE_PASSWORD=FALSE
  DEFAULT_WAREHOUSE='DBT_WH'
  DEFAULT_ROLE='dbt'
GRANT ROLE dbt to USER dbt_user;*/

-- Create our database and schemas
CREATE DATABASE IF NOT EXISTS ANALYTICS;
CREATE SCHEMA IF NOT EXISTS RAW;

-- Set up permissions to role `dbt`
GRANT ALL ON WAREHOUSE DBT_WH TO ROLE dbt; 
GRANT ALL ON DATABASE ANALYTICS to ROLE dbt;
GRANT ALL ON ALL SCHEMAS IN DATABASE ANALYTICS to ROLE dbt;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE ANALYTICS to ROLE dbt;
GRANT ALL ON ALL TABLES IN SCHEMA ANALYTICS.RAW to ROLE dbt;
GRANT ALL ON FUTURE TABLES IN SCHEMA ANALYTICS.RAW to ROLE dbt;

show grants to role dbt
SHOW GRANTS ON SCHEMA ANALYTICS.RAW;