ALTER TABLE DATABASE.SCHEMA.TABLE
ADD COLUMN IF NOT EXISTS PARTITION_COL VARCHAR DEFAULT '';

-- Create a temporary table with transformed data
CREATE OR REPLACE TEMPORARY TABLE TEMP_TRANSFORMED_TABLE AS
SELECT
  *,
  EXTRACT(YEAR FROM DATE_COL) AS PARTITION_COL
FROM DATABASE.SCHEMA.TABLE;

-- Copy data from the temporary table back to the original table
INSERT OVERWRITE INTO DATABASE.SCHEMA.TABLE
SELECT * FROM TEMP_TRANSFORMED_TABLE;